insert into Category (name) values ('Foods');
insert into Category (name) values ('Drinks');
insert into Category (name) values ('Fashion');
insert into Category (name) values ('Mens');
insert into Category (name) values ('Girls');
insert into Category (name) values ('Electrict Device');
insert into Category (name) values ('Music');
insert into Category (name) values ('Videos');
insert into Category (name) values ('Mobile and Accessories');

insert into township (division_id, name) values (1, 'Hinthada');
insert into township (division_id, name) values (1, 'Lemyethna');
insert into township (division_id, name) values (1, 'Zalun');
insert into township (division_id, name) values (1, 'Ithapyu');
insert into township (division_id, name) values (1, 'Labutta');
insert into township (division_id, name) values (1, 'Mawlamyinegyun');
insert into township (division_id, name) values (1, 'Kyonmanage');
insert into township (division_id, name) values (1, 'Pyinsalu');
insert into township (division_id, name) values (1, 'Danubyu');
insert into township (division_id, name) values (1, 'Ma-ubin');
insert into township (division_id, name) values (1, 'Nyaungdon');
insert into township (division_id, name) values (1, 'Pantanaw');
insert into township (division_id, name) values (1, 'Einme');
insert into township (division_id, name) values (1, 'Myaungmya');
insert into township (division_id, name) values (1, 'Wakema');
insert into township (division_id, name) values (1, 'Shwelaung');
insert into township (division_id, name) values (1, 'Kangyidaunk');
insert into township (division_id, name) values (1, 'Ngapudaw');
insert into township (division_id, name) values (1, 'Pathein');
insert into township (division_id, name) values (1, 'Thabaung');
insert into township (division_id, name) values (1, 'Chaungtha');
insert into township (division_id, name) values (1, 'Hainggyi');
insert into township (division_id, name) values (1, 'Ngayokekaung');
insert into township (division_id, name) values (1, 'Ngwesaung');
insert into township (division_id, name) values (1, 'Bogale');
insert into township (division_id, name) values (1, 'Dedaye');
insert into township (division_id, name) values (1, 'Kyaiklat');
insert into township (division_id, name) values (1, 'Pyapon');
insert into township (division_id, name) values (1, 'Ahmar');
insert into township (division_id, name) values (1, 'Kyaunggon');
insert into township (division_id, name) values (1, 'Kyonpyaw');
insert into township (division_id, name) values (1, 'Yekyi');
insert into township (division_id, name) values (1, 'Ahtaung');
insert into township (division_id, name) values (1, 'Ngathinechaung');
insert into township (division_id, name) values (1, 'Ingapu');
insert into township (division_id, name) values (1, 'Kyangin');
insert into township (division_id, name) values (1, 'Myanaung');
insert into township (division_id, name) values (1, 'Kanaung');

insert into township (division_id, name) values(2, 'Bago');
insert into township (division_id, name) values(2, 'Daik-U');
insert into township (division_id, name) values(2, 'Kawa');
insert into township (division_id, name) values(2, 'Nyaunglebin');
insert into township (division_id, name) values(2, 'Shwegyin');
insert into township (division_id, name) values(2, 'Thanatpin');
insert into township (division_id, name) values(2, 'Waw');
insert into township (division_id, name) values(2, 'Kyauktaga');
insert into township (division_id, name) values(2, 'Kyaukkyi');
insert into township (division_id, name) values(2, 'Oktwin');
insert into township (division_id, name) values(2, 'Pyu');
insert into township (division_id, name) values(2, 'Tantabin');
insert into township (division_id, name) values(2, 'Taungoo');
insert into township (division_id, name) values(2, 'Yedashe');
insert into township (division_id, name) values(2, 'Pandaung');
insert into township (division_id, name) values(2, 'Paukkaung');
insert into township (division_id, name) values(2, 'Paungde');
insert into township (division_id, name) values(2, 'Pyay');
insert into township (division_id, name) values(2, 'Shwedaung');
insert into township (division_id, name) values(2, 'Thegon');
insert into township (division_id, name) values(2, 'Gyobingauk');
insert into township (division_id, name) values(2, 'Letpadan');
insert into township (division_id, name) values(2, 'Minhla');
insert into township (division_id, name) values(2, 'Monyo');
insert into township (division_id, name) values(2, 'Okpho');
insert into township (division_id, name) values(2, 'Tharrawaddy');
insert into township (division_id, name) values(2, 'Nattalin');
insert into township (division_id, name) values(2, 'Zigon');

insert into township (division_id, name) values(3, 'Falam');
insert into township (division_id, name) values(3, 'Tiddim');
insert into township (division_id, name) values(3, 'Ton Zang');
insert into township (division_id, name) values(3, 'Hakha');
insert into township (division_id, name) values(3, 'Htantlang');
insert into township (division_id, name) values(3, 'Matupi');
insert into township (division_id, name) values(3, 'Paletwa');
insert into township (division_id, name) values(3, 'Kanpetlet');
insert into township (division_id, name) values(3, 'Mindat');

