insert into Division (name) values ('Ayeyarwady Region');
insert into Division (name) values ('Bago Region');
insert into Division (name) values ('Chin State');
insert into Division (name) values ('Kachin State');
insert into Division (name) values ('Kayah State');
insert into Division (name) values ('Kayin State');
insert into Division (name) values ('Magway Region');
insert into Division (name) values ('Mandalay Region');
insert into Division (name) values ('Mon State');
insert into Division (name) values ('Rakhine State');
insert into Division (name) values ('Shan State');
insert into Division (name) values ('Sagaing Region');
insert into Division (name) values ('Tanintharyi Region');
insert into Division (name) values ('Yangon Region');
insert into Division (name) values ('Naypyidaw Union Territory');

insert into township (name, division_id) values ('Bago Township', 2);
insert into township (name, division_id) values ('Daik-U Township', 2);
insert into township (name, division_id) values ('Kawa Township', 2);
insert into township (name, division_id) values ('Nyaunglebin Township', 2);
insert into township (name, division_id) values ('Shwegyin Township', 2);
insert into township (name, division_id) values ('Thanatpin Township', 2);
insert into township (name, division_id) values ('Waw Township', 2);
insert into township (name, division_id) values ('Kyauktaga Township', 2);
insert into township (name, division_id) values ('Kyaukkyi Township', 2);
insert into township (name, division_id) values ('Oktwin Township', 2);
insert into township (name, division_id) values ('Pyu Township', 2);
insert into township (name, division_id) values ('Tantabin Township', 2);
insert into township (name, division_id) values ('Taungoo Township', 2);
insert into township (name, division_id) values ('Yedashe Township', 2);
insert into township (name, division_id) values ('Pandaung Township', 2);
insert into township (name, division_id) values ('Paukkaung Township', 2);
insert into township (name, division_id) values ('Paungde Township', 2);
insert into township (name, division_id) values ('Pyay Township', 2);
insert into township (name, division_id) values ('Shwedaung Township', 2);
insert into township (name, division_id) values ('Thegon Township', 2);
insert into township (name, division_id) values ('Gyobingauk Township', 2);
insert into township (name, division_id) values ('Letpadan Township', 2);
insert into township (name, division_id) values ('Minhla Township', 2);
insert into township (name, division_id) values ('Monyo Township', 2);
insert into township (name, division_id) values ('Okpho Township', 2);
insert into township (name, division_id) values ('Tharrawaddy Township', 2);
insert into township (name, division_id) values ('Nattalin Township', 2);
insert into township (name, division_id) values ('Zigon Township', 2);

insert into township (name, division_id) values ('Falam Township', 3);
insert into township (name, division_id) values ('Tiddim Township', 3);
insert into township (name, division_id) values ('Ton Zang Township', 3);
insert into township (name, division_id) values ('Hakha Township', 3);
insert into township (name, division_id) values ('Htantlang Township', 3);
insert into township (name, division_id) values ('Matupi Township', 3);
insert into township (name, division_id) values ('Paletwa Township', 3);
insert into township (name, division_id) values ('Kanpetlet Township', 3);
insert into township (name, division_id) values ('Mindat Township', 3);

insert into Address (street, township_id) values ('Bago Township Street 1', 1);
insert into Address (street, township_id) values ('Bago Township Street 2', 1);
insert into Address (street, township_id) values ('Bago Township Street 3', 1);
insert into Address (street, township_id) values ('Kawa Township Street 4', 3);
insert into Address (street, township_id) values ('Kawa Township Street 5', 3);
insert into Address (street, township_id) values ('Kawa Township Street 6', 3);
insert into Address (street, township_id) values ('Kawa Township Street 7', 3);
insert into Address (street, township_id) values ('Pyu Township Street 8', 11);
insert into Address (street, township_id) values ('Pyu Township Street 9', 11);
insert into Address (street, township_id) values ('Pyu Township Street 10', 11);
insert into Address (street, township_id) values ('Pyu Township Street 11', 11);
insert into Address (street, township_id) values ('Tiddim Township Street 12', 30);
insert into Address (street, township_id) values ('Tiddim Township Street 13', 30);
insert into Address (street, township_id) values ('Tiddim Township Street 14', 30);
insert into Address (street, township_id) values ('Tiddim Township Street 15', 30);
insert into Address (street, township_id) values ('Tiddim Township Street 16', 30);
insert into Address (street, township_id) values ('Matupi Township Street 17', 34);
insert into Address (street, township_id) values ('Matupi Township Street 18', 34);
insert into Address (street, township_id) values ('Matupi Township Street 19', 34);
insert into Address (street, township_id) values ('Matupi Township Street 20', 34);
insert into Address (street, township_id) values ('Mindat Township Street 21', 37);
insert into Address (street, township_id) values ('Mindat Township Street 22', 37);
insert into Address (street, township_id) values ('Mindat Township Street 23', 37);
insert into Address (street, township_id) values ('Mindat Township Street 24', 37);

insert into Customer (name, phone, email, address_id) values ('Customer 1', '09-8688-91', 'customer1@gmail.com', 1);
insert into Customer (name, phone, email, address_id) values ('Customer 2', '09-8688-92', 'customer2@gmail.com', 2);
insert into Customer (name, phone, email, address_id) values ('Customer 3', '09-8688-93', 'customer3@gmail.com', 3);
insert into Customer (name, phone, email, address_id) values ('Customer 4', '09-8688-94', 'customer4@gmail.com', 4);
insert into Customer (name, phone, email, address_id) values ('Customer 5', '09-8688-95', 'customer5@gmail.com', 5);
insert into Customer (name, phone, email, address_id) values ('Customer 6', '09-8688-96', 'customer6@gmail.com', 6);
insert into Customer (name, phone, email, address_id) values ('Customer 7', '09-8688-97', 'customer7@gmail.com', 7);
insert into Customer (name, phone, email, address_id) values ('Customer 8', '09-8688-98', 'customer8@gmail.com', 8);
insert into Customer (name, phone, email, address_id) values ('Customer 9', '09-8688-99', 'customer9@gmail.com', 9);
insert into Customer (name, phone, email, address_id) values ('Customer 10', '09-8688-910', 'customer10@gmail.com', 10);
insert into Customer (name, phone, email, address_id) values ('Customer 11', '09-8688-911', 'customer11@gmail.com', 11);
insert into Customer (name, phone, email, address_id) values ('Customer 12', '09-8688-912', 'customer12@gmail.com', 12);
insert into Customer (name, phone, email, address_id) values ('Customer 13', '09-8688-913', 'customer13@gmail.com', 13);
insert into Customer (name, phone, email, address_id) values ('Customer 14', '09-8688-914', 'customer14@gmail.com', 14);
insert into Customer (name, phone, email, address_id) values ('Customer 15', '09-8688-915', 'customer15@gmail.com', 15);
insert into Customer (name, phone, email, address_id) values ('Customer 16', '09-8688-916', 'customer16@gmail.com', 16);
insert into Customer (name, phone, email, address_id) values ('Customer 17', '09-8688-917', 'customer17@gmail.com', 17);
insert into Customer (name, phone, email, address_id) values ('Customer 18', '09-8688-918', 'customer18@gmail.com', 18);
insert into Customer (name, phone, email, address_id) values ('Customer 19', '09-8688-919', 'customer19@gmail.com', 19);
insert into Customer (name, phone, email, address_id) values ('Customer 20', '09-8688-920', 'customer20@gmail.com', 20);
insert into Customer (name, phone, email, address_id) values ('Customer 21', '09-8688-921', 'customer21@gmail.com', 21);
insert into Customer (name, phone, email, address_id) values ('Customer 22', '09-8688-922', 'customer22@gmail.com', 22);
insert into Customer (name, phone, email, address_id) values ('Customer 23', '09-8688-923', 'customer23@gmail.com', 23);
insert into Customer (name, phone, email, address_id) values ('Customer 24', '09-8688-924', 'customer24@gmail.com', 24);

insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (1, 180000 ,'2020-07-10', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (2, 350000 ,'2020-07-10', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (5, 210000 ,'2020-07-10', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (22, 1120000 ,'2020-07-15', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (20, 5300000 ,'2020-07-15', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (5, 340000 ,'2020-07-15', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (20, 150000 ,'2020-07-15', '2020-07-30');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (1, 500000 ,'2020-08-01', '2020-08-15');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (5, 1200000 ,'2020-08-01', '2020-08-15');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (18, 250000 ,'2020-08-01', '2020-08-15');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (1, 100000 ,'2020-08-01', '2020-08-15');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (17, 150000 ,'2020-08-01', '2020-08-15');
insert into invoice(customer_id, paid_amount, invoice_date, paid_date) values (10, 3000000 ,'2020-08-01', '2020-08-15');
